import type { Metadata } from "next";
import { baskerville } from '@/app/ui/font'
import { SideNav } from '@/app/components/nav'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang = "en">
      <body className = {`${baskerville.className} antialiased flex h-screen flex-col md:flex-row md:overflow-hidden`}>
        <div className = "w-full flex-none md:w-64">
          <SideNav />
        </div>
        <div className = "flex-grow m-2 overflow-auto"> {children} </div>
      </body>
    </html>
  );
}
